name: Scrape

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "23 */6 * * *"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.is_template }}
    outputs:
      changes_detected: ${{ steps.commit.outputs.changes_detected }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Download latest routeviews and process
        run: uv run --python 3.12 --script download_ribs.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add routeviews*.json*
          git diff --quiet && git diff --staged --quiet || git commit -m "Update ASN prefix data"
          git push

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: scrape
    if: ${{ needs.scrape.outputs.changes_detected == 'true' }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
